apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: polling-app
spec:
  selector:
    matchLabels:
      app: polling-app
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: polling-app
        tier: mysql
    spec:
      containers:
        - image: arm64v8/mariadb:10.6.4-focal
          imagePullPolicy: Always
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name:  mysql-secrets
                  key: root-password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: database
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: password
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
      imagePullSecrets:
        - name: regcred
