apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: kubernetes.io/basic-auth
stringData:
  username: admin
  password: t0p-Secret
  root-password: password
  database: db
  url: jdbc:mysql://polling-app-mysql:3306/db