apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  labels:                     # Labels that will be applied to this resource
    app: {{ .Values.app.name }}
spec:
  selector:
    app: {{ .Values.app.name }}   # The service exposes Pods with label `app=polling-app-server`
  ports:                      # Forward incoming connections on port 8080 to the target port 8080
    - name: http
      port: {{ .Values.app.containerPort }}